# Guided Capstone Step 6. Documentation

**The Data Science Method**  


1.   Problem Identification 

2.   Data Wrangling 
  
3.   Exploratory Data Analysis 
 
4.   Pre-processing and Training Data Development

5.  Modeling

6.   **Documentation**
  * Review the Results
  * Finalize Code 
  * Finalize Documentation
  * Create a Project Report 
  * Create a Slide Deck for the Executive Audience

In this guided capstone we are going to revisit many of the actions we took in the previous guided capstone steps. This gives you the opportunity to practice the code you wrote to solve the questions in step 4 and 5. 

**<font color='teal'> Start by loading the necessary packages and printing out our current working directory just to confirm we are in the correct project directory. </font>**

In [1]:
#load python packages
import os
import pandas as pd
import datetime
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
os.getcwd()

'C:\\Users\\brenden.lemay'

In [5]:
os.chdir('.\Downloads\capstone')

In [6]:
os.getcwd()

'C:\\Users\\brenden.lemay\\Downloads\\capstone'

In [53]:
df = pd.read_csv('.\step3_output3.csv')
df.drop(['Unnamed: 0'], axis=1, inplace=True)

## Fit Models with Training Dataset

**<font color='teal'> Using sklearn fit the model you chose in Guided Capstone 5 on your training dataset. This includes: creating dummy features for states if you need them, scaling the data,and creating train and test splits before fitting the chosen model.Also, remember to generate a model performance score(MAE, or explained variance) based on the testing hold-out data set.</font>**

#### Best Model 

In [54]:
# first we import the preprocessing package from the sklearn library
from sklearn import preprocessing

# Declare an explanatory variable, called X,and assign it the result of dropping 'Name', 'AdultWeekend', 'Region', 'state'
# , 'base_elev', 'summit_elev' and 'vertical_drop'
# from the df
X = df.drop(['Name','AdultWeekend','Region','state', 'summit_elev', 'vertical_drop'], axis=1)

# Declare a response variable, called y, and assign it the AdultWeekend column of the df 
y = df.AdultWeekend 

# Here we use the StandardScaler() method of the preprocessing package, and then call the fit() method with parameter X 
scaler = preprocessing.StandardScaler().fit(X)

# Declare a variable called X_scaled, and assign it the result of calling the transform() method with parameter X 
X_scaled=scaler.transform(X) 

In [89]:
X_scaled[141]

array([-0.14798528, -0.27440432,  0.        , -0.27741869,  1.45675982,
        1.01152332,  2.96723292, -1.07614016,  0.29256569,  1.56584118,
        1.86869881,  0.88810911,  1.95735125,  3.46024135,  3.47359599,
        0.54545017,  0.83254656,  1.23711617,  1.14753809,  0.41842245,
        5.80844975,  0.64447804])

In [55]:
# Import the train_test_split function from the sklearn.model_selection utility.  
from sklearn.model_selection import train_test_split

# Get the 1-dimensional flattened array of our response variable y by calling the ravel() function on y
y = y.ravel()

# Call the train_test_split() function with the first two parameters set to X_scaled and y 
# Declare four variables, X_train, X_test, y_train and y_test separated by commas 
X_train, X_test, y_train , y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=1)

In [56]:
#all third model set
from sklearn import linear_model
from sklearn.metrics import explained_variance_score,mean_absolute_error
lm = linear_model.LinearRegression()
model = lm.fit(X_train,y_train)

In [57]:
y_pred = model.predict(X_test)

In [78]:
X_test

array([[-0.74430913, -0.27440432,  0.        , ..., -2.0432684 ,
         0.45019664, -0.70979676],
       [ 0.45898721, -0.27440432,  0.        , ...,  0.37839495,
         0.45019664, -0.70979676],
       [ 1.72617539, -0.27440432,  0.        , ...,  0.41842245,
         0.5573617 ,  0.64447804],
       ...,
       [-0.1799312 , -0.27440432,  0.        , ...,  0.67860115,
        -0.62145399,  1.99875283],
       [-1.2660925 ,  2.77344371,  0.        , ...,  0.97880735,
        -0.62145399,  1.99875283],
       [ 0.57612225, -0.27440432,  0.        , ..., -2.0432684 ,
         0.39661411,  0.64447804]])

In [80]:
X_train

array([[ 0.39509537, -0.27440432,  0.        , ..., -2.0432684 ,
         0.5573617 , -0.70979676],
       [-0.41420129, -0.27440432,  0.        , ...,  0.19827123,
        -0.13921121, -0.70979676],
       [ 1.55579715, -0.27440432,  0.        , ...,  0.65858741,
         1.52184726, -0.70979676],
       ...,
       [-0.91468738, -0.27440432,  0.        , ...,  0.29833997,
        -0.13921121, -0.70979676],
       [ 0.86363553, -0.27440432,  0.        , ..., -0.10193497,
         0.45019664, -0.70979676],
       [-1.29803842, -0.27440432,  0.        , ...,  0.65858741,
        -0.62145399,  1.99875283]])

In [58]:
from sklearn.metrics import explained_variance_score, mean_absolute_error
# Getting explained_variance_score
explained_variance_score(y_test, y_pred)

0.12302240574491097

In [59]:
mean_absolute_error(y_test, y_pred)

17.722598462972726

In [60]:
lm.intercept_

53.17688475415207

In [61]:
# Creating a pandas DataFrame displaying the coefficients for each column like so: 
pd.DataFrame(abs(lm.coef_), X.columns, columns=['Coefficient']).sort_values(by='Coefficient',ascending=False).head(10)


Coefficient
AdultWeekday      22.745911
TerrainParks       4.902666
Runs               4.705120
trams              4.464873
fastQuads          3.819995
clusters           3.398345
Snow Making_ac     2.830311
quad               2.761112
surface            2.752340
LongestRun_mi      2.687025

## Review the results 

**<font color='teal'> Now, let's predict the Big Mountain Weekend price with our model in order to provide a recommendation to our managers on how to price the `AdultWeekend` lift ticket. First we need to find the row for Big Mountain resort in our data using string contains or string matching.</font>**

In [62]:
df[df['Name'].str.contains('Big Mountain')]

Unnamed: 0.1                 Name   Region    state  summit_elev  \
141           151  Big Mountain Resort  Montana  Montana         6817   

     vertical_drop  trams  fastEight  fastSixes  fastQuads  ...  \
141           2353      0        0.0          0          3  ...   

     SkiableTerrain_ac  Snow Making_ac  daysOpenLastYear  yearsOpen  \
141             3000.0           600.0             123.0       72.0   

     averageSnowfall  AdultWeekday  AdultWeekend  projectedDaysOpen  \
141            333.0          81.0          81.0              123.0   

     NightSkiing_ac  clusters  
141           600.0         1  

[1 rows x 28 columns]

In [79]:
df.iloc[141]

Unnamed: 0.1                         151
Name                 Big Mountain Resort
Region                           Montana
state                            Montana
summit_elev                         6817
vertical_drop                       2353
trams                                  0
fastEight                              0
fastSixes                              0
fastQuads                              3
quad                                   2
triple                                 6
double                                 0
surface                                3
total_chairs                          14
Runs                                 105
TerrainParks                           4
LongestRun_mi                        3.3
SkiableTerrain_ac                   3000
Snow Making_ac                       600
daysOpenLastYear                     123
yearsOpen                             72
averageSnowfall                      333
AdultWeekday                          81
AdultWeekend    

**<font color='teal'> Prepare the Big Mountain resort data row as you did in the model fitting stage.</font>**

In [87]:
X_bigM = df.iloc[141].drop(['Name','AdultWeekend','Region','state', 'summit_elev', 'vertical_drop'])
type(X_bigM)

pandas.core.series.Series

In [83]:
# first we import the preprocessing package from the sklearn library
from sklearn import preprocessing

# Declare an explanatory variable, called X,and assign it the result of dropping 'Name', 'AdultWeekend', 'Region', 'state'
# , 'base_elev', 'summit_elev' and 'vertical_drop'
# from the df
X_bigM = df.iloc[141].drop(['Name','AdultWeekend','Region','state', 'summit_elev', 'vertical_drop'])

# Declare a response variable, called y, and assign it the AdultWeekend column of the df 
y = df.AdultWeekend 

# Here we use the StandardScaler() method of the preprocessing package, and then call the fit() method with parameter X 
scaler = preprocessing.StandardScaler().fit(X_bigM)

# Declare a variable called X_scaled, and assign it the result of calling the transform() method with parameter X 
X_scaled=scaler.transform(X_bigM) 

ValueError: Expected 2D array, got 1D array instead:
array=[1.51e+02 0.00e+00 0.00e+00 0.00e+00 3.00e+00 2.00e+00 6.00e+00 0.00e+00
 3.00e+00 1.40e+01 1.05e+02 4.00e+00 3.30e+00 3.00e+03 6.00e+02 1.23e+02
 7.20e+01 3.33e+02 8.10e+01 1.23e+02 6.00e+02 1.00e+00].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [91]:
from sklearn import linear_model
from sklearn.metrics import explained_variance_score,mean_absolute_error
lm = linear_model.LinearRegression()
model = lm.fit(X_train, y_train)

In [94]:
y_test

array([47.  , 57.  , 59.  , 59.  , 60.  , 59.  , 49.  ,  0.  , 47.  ,
       70.  , 99.  , 33.  , 55.  ,  0.  , 84.  , 49.  , 79.  , 92.  ,
       69.  , 35.  , 42.  , 48.  ,  0.  , 55.  ,  0.  , 38.  , 47.  ,
       89.  , 67.  ,  0.  , 72.  ,  0.  , 72.  ,  0.  , 89.  , 59.  ,
       25.  , 47.  , 35.  , 89.  , 41.  , 44.  , 60.  , 59.  ,  0.  ,
       45.  , 98.  , 44.  , 77.  , 81.  , 42.  , 44.  , 78.  , 80.  ,
       69.  , 47.  , 35.34, 49.  , 78.  , 49.  ,  0.  , 42.  , 75.  ,
       85.  , 54.  , 49.  , 45.  , 17.  , 39.  , 20.  , 49.  , 44.  ,
       85.  , 69.  , 66.  , 67.  ,  0.  , 68.  ])

**<font color='teal'> Predict the Big Mountain resort `Adult Weekend` price and print it out.</font>** This is our expected price to present to management. Based on our model given the characteristics of the resort in comparison to other ski resorts and their unique characteristics.

**<font color='teal'> Print the Big Mountain resort actual `Adult Weekend` price.</font>**

**<font color='teal'> As part of reviewing the results it is an important step to generate figures to visualize the data story. We can use the clusters we added to our data frame to create scatter plots for visualizing the Adult Weekend values compared to other characteristics. Run the example below to get you started and build two or three more figures to include in your data story telling.</font>**

In [0]:
#plt.scatter(df['summit_elev'], df['vertical_drop'], c=df['clusters'], s=50, cmap='viridis', label ='clusters')
#plt.scatter(ac['summit_elev'], ac['vertical_drop'], c='black', s=100)
#plt.xlabel('summit_elev')
#plt.ylabel('vertical_drop')
#plt.title('summit_elev by vertical_drop by cluster')
#plt.savefig('figures/fig1.png',bbox_inches='tight')

## Finalize Code

 Making sure our code is well organized and easy to follow is an important step. This is the time where you need to review the notebooks and Python scripts you've created and clean them up so they are easy to follow and succinct in nature. Addtionally, we will also save our final model as a callable object using Pickle for future use in a data pipeline. Pickle is a module that serializes (and de-serializes) Python objects so that they can become executable objects like functions. It's used extensively in production environments where machine learning models are deployed on an industrial scale!**<font color='teal'> Run the example code below to save out your callable model. Notice that we save it in the models folder we created in our previous guided capstone step.</font>** 

In [0]:
#import pickle
#s = pickle.dumps(model)
#from joblib import dump, load
#dump(model, 'models/regression_model_adultweekend.joblib') 

## Finalize Documentation

For model documentation, we want to save the model performance metrics as well as the features included in the final model. You could also save the model perfomance metrics and coefficients fo the other models you tried in case you want to refer to them later. **<font color='teal'> Create a dataframe containing the coefficients and the model performance metrics and save it out as a csv file, then upload it to your github repository.</font>** 